pekko.grpc.client {
  "at.fhv.sysarch.lab2.homeautomation.grpcdemo.OrderService" {
    host = 127.0.0.1
    port = 8080
    use-tls = false
  }
}

pekko.actor.allow-java-serialization = on

pekko.persistence.journal.plugin        = "jdbc-journal"
pekko.persistence.snapshot-store.plugin = "jdbc-snapshot-store"

jdbc-journal.slick        = ${slick}
jdbc-snapshot-store.slick = ${slick}
jdbc-read-journal.slick   = ${slick}

slick {
  profile = "slick.jdbc.H2Profile$"
  db {
    url            = "jdbc:h2:./pekkojournal;DATABASE_TO_UPPER=false"
    driver         = "org.h2.Driver"
    numThreads     = 2
    maxConnections = 2
    minConnections = 1
  }
}